課題4. 本のバーコードをスキャンしてISBN値を元にAmazonの商品ページを表示する #4
kobayashi-shota/flutter_study pull request #14
Opened 2023-06-07 08:16 UTC by kobayashi-shota

## バーコード
- [ ] スキャン機能実装
- [ ] スキャン結果解析（ISBNCodeかCheck）

## Webページ
- [ ] Webページ表示機能
- [ ] 値渡しで受け取ったURLでの表示

2023-06-12 08:03 UTC, kobayashi-shota commented
@fujiki-yuya cc @MinatoIshiwata 
Draftの時に間違えてRequest送ってしまってたんですが、Ready for reviewになったのでお手隙でReviewお願いします🙏🏻

2023-06-13 02:02 UTC, fujiki-yuya reviewed
@kobayashi-shota 
1件コメントしました。🙇‍♂

2023-06-13 02:03 UTC, fujiki-yuya reviewed
@kobayashi-shota 
1件コメントしました。🙇‍♂

2023-06-13 02:03 UTC, fujiki-yuya commented on lib/presentation/screen/search_books_top_screen.dart
> +  final _cancelController = TextEditingController(text: 'Cancel');
こちらdisposeすると良いかと思います。
https://api.flutter.dev/flutter/widgets/TextEditingController-class.html

2023-06-14 00:14 UTC, kobayashi-shota commented on lib/presentation/screen/search_books_top_screen.dart
> +  final _cancelController = TextEditingController(text: 'Cancel');
@fujiki-yuya cc @MinatoIshiwata 
disposeするかcontrollerを消すかの2択で、ScanOptionのデフォルト文言と同じ文言を指定してたのでControllerを削除しました🙏🏻
[fix: default文言と重複するためscanOptions削除](https://github.com/kobayashi-shota/flutter_study/pull/14/commits/a0ab4a5d0ce82e72434b4e4ac14dbdda17f5ee65)

2023-06-14 18:28 UTC, MinatoIshiwata commented on lib/core/extension/int_extension.dart
> +    final weights = <int>[10, 9, 8, 7, 6, 5, 4, 3, 2];
こちらList.generateを使うとスッキリするかと思います🙋

2023-06-14 18:29 UTC, MinatoIshiwata commented on lib/core/extension/int_extension.dart
> +      11 => '0',
マジックナンバではなく名称をつけていただきたいです🙋

2023-06-14 18:30 UTC, MinatoIshiwata commented on lib/core/extension/int_extension.dart
> +      10 => '0',
マジックナンバではなく名称をつけていただきたいです🙋

2023-06-14 18:30 UTC, MinatoIshiwata commented on lib/core/extension/int_extension.dart
> +        checkSum += digit * 3;
マジックナンバではなく名称をつけていただきたいです🙋

2023-06-14 18:31 UTC, MinatoIshiwata commented on lib/presentation/screen/webview_screen.dart
> +      body: Column(
SafeArea追加頂いたほうが良いかもです🙋

2023-06-14 18:32 UTC, MinatoIshiwata requested changes
@kobayashi-shota 
何点かコメントいたしました🙋
ご確認のほどよろしくお願いいたします。

2023-06-15 00:15 UTC, kobayashi-shota commented on lib/core/extension/int_extension.dart
> +    final weights = <int>[10, 9, 8, 7, 6, 5, 4, 3, 2];
修正コミットです🙏🏻
[fix: weightsをList.generateで生成](https://github.com/kobayashi-shota/flutter_study/pull/14/commits/c64672ec0a93b7df3694fa63c4fea17495b01b91)

2023-06-15 00:35 UTC, kobayashi-shota commented on lib/core/extension/int_extension.dart
> +      11 => '0',
ここの処理ですが、１１（== modulus）になった際は必ず０になるので判断不要だったため
０かどうかだけ判断するように改修しました🙏🏻
[fix: modulus11のcheckDigit確定処理見直し](https://github.com/kobayashi-shota/flutter_study/pull/14/commits/058c165515b887610193762ec18a12a8a936ebe9)

2023-06-15 00:39 UTC, kobayashi-shota commented on lib/core/extension/int_extension.dart
> +      10 => '0',
修正コミットです🙏🏻
[fix: 10をmodulusに置換](https://github.com/kobayashi-shota/flutter_study/pull/14/commits/ac020e74e11e90109f576a24bcef51493aa96f45)

2023-06-15 00:42 UTC, kobayashi-shota commented on lib/core/extension/int_extension.dart
> +        checkSum += digit * 3;
修正コミットです🙏🏻
[fix: 3をweightに置換](https://github.com/kobayashi-shota/flutter_study/pull/14/commits/a54b94e72b34b6f6f2a116f0d810e7fe88d2176e)

2023-06-15 00:54 UTC, kobayashi-shota commented on lib/presentation/screen/webview_screen.dart
> +      body: Column(
landscapeの確認漏れてました🙇🏻‍♂️
修正コミットです🙏🏻
[fix: webviewをSafeAreaにEmbedする](https://github.com/kobayashi-shota/flutter_study/pull/14/commits/285c82e68aeb7864a877ed28b17c94e9c5617029)

| before | after |
|--------|--------|
| ![IMG_2944](https://github.com/kobayashi-shota/flutter_study/assets/82574685/02dccec8-1cc4-401c-b57e-c0e175af6b58)|![IMG_847FC42AE190-1](https://github.com/kobayashi-shota/flutter_study/assets/82574685/14884923-9f92-40c3-bede-4c1b2a5afa73)|

2023-06-15 00:55 UTC, kobayashi-shota commented
@MinatoIshiwata 
ご指摘分修正完了しましたので、お手隙でレビューお願いします🙏🏻

2023-06-16 00:59 UTC, MinatoIshiwata commented on lib/presentation/screen/search_books_top_screen.dart
> +              ListView(
Columnがいらないかと思いますがいかがでしょうか？

2023-06-16 01:00 UTC, MinatoIshiwata approved these changes
@kobayashi-shota 
1点だけご確認のほどよろしくお願いいたします。

2023-06-16 02:41 UTC, kobayashi-shota commented on lib/presentation/screen/search_books_top_screen.dart
> +              ListView(
Column不要ですね😅
[fix: 不要なColumnの削除](https://github.com/kobayashi-shota/flutter_study/pull/14/commits/b5186686181ace2852d4d1b6d0370415130a2a2f)

2023-06-16 02:54 UTC, merged