fix: 課題5. GitHub APIを利用して、指定したリポジトリの情報を取得し、リスト形式で表示するアプリを作成する
kobayashi-shota/flutter_study pull request #18
Opened 2023-06-16 02:21 UTC by kobayashi-shota

## 概要
#5 

## 変更点
- GitHub Rest API(/search/repositories）からデータを取得して画面にList表示します

![Simulator Screen Recording - iPhone SE (1st generation) - 2023-06-16 at 11 05 34](https://github.com/kobayashi-shota/flutter_study/assets/82574685/2f6cfc8c-57cd-4d9d-8d74-010ce3d5575d)

![Simulator Screenshot - iPhone 14 Pro Max - 2023-06-16 at 11 10 20](https://github.com/kobayashi-shota/flutter_study/assets/82574685/c0164e07-539d-4b98-a280-5f8b78e47e67)

## 懸念点
- リポジトリ以外の情報検索・検索履歴の実装や、データ取得処理の分離まで実施したかったんですが、若干時間の余裕が無くなってきたので断念しました

2023-06-19 07:05 UTC, utamori commented on lib/presentation/screen/search_github_repo_screen.dart
> +            );
onEditingComplete じゃなくonSubmittedを使うと、エンター押した時の値が取得できるので簡潔になります

2023-06-19 07:08 UTC, utamori commented on lib/presentation/screen/search_github_result_screen.dart
> +                  imageUrl: repo.owner.avatarUrl!,
! bangは実行エラー可能性あるので、nullの場合はleadingを別のアイコンにするなどの処理にする

2023-06-19 07:09 UTC, utamori requested changes
レビューしました

2023-06-19 07:16 UTC, kobayashi-shota commented on lib/presentation/screen/search_github_repo_screen.dart
> +            );
修正しました、確かにcontroller書かなくて良くなるから簡潔ですね👍
[fix: 検索キーワードはonSubmittedで渡す](https://github.com/kobayashi-shota/flutter_study/pull/18/commits/4b7d636d6bf4a67e61772c7af9b323538ae36d8b)

2023-06-19 07:31 UTC, kobayashi-shota commented on lib/presentation/screen/search_github_result_screen.dart
> +                  imageUrl: repo.owner.avatarUrl!,
修正しました🙏🏻
[fix: avatarUrlがnullの際の対策](https://github.com/kobayashi-shota/flutter_study/pull/18/commits/534f53bf68eb4b33de47c9fe7aa47e811eb9f26e)

2023-06-19 09:12 UTC, utamori requested changes

2023-06-19 09:12 UTC, utamori commented on lib/presentation/screen/search_github_result_screen.dart
> +                      ),
`!`を使わない方がいい
nullablleから非nullにするには、switch式を使うといい
final url? => みたいにするとそのスコープでは url変数は非nullとして使える
https://dart.dev/language/pattern-types#null-check

2023-06-20 00:25 UTC, kobayashi-shota commented on lib/presentation/screen/search_github_result_screen.dart
> +                      ),
修正しました、こんな感じですかね？
[fix: switch式内でavatarUrlを非nullとして扱うよう修正](https://github.com/kobayashi-shota/flutter_study/pull/18/commits/e8213577e49575bdd89fe4fd95239d96b237eb33)

2023-06-20 00:34 UTC, utamori commented on lib/presentation/screen/search_github_result_screen.dart
> +                      ),
それでも良いけど、

final avatorUrl?=>
_=>

でもいける

2023-06-20 00:40 UTC, kobayashi-shota commented on lib/presentation/screen/search_github_result_screen.dart
> +                      ),
理解しました🙏🏻
[fix: avatarUrl?と宣言して非nullで扱う](https://github.com/kobayashi-shota/flutter_study/pull/18/commits/56af1bc1935fc4a711f713679a9d46a47e2e63e7)

2023-06-20 07:47 UTC, MinatoIshiwata approved these changes
LGTM

2023-06-20 08:17 UTC, merged