fix: 課題6-1. ニュースAPIを利用して、最新のニュースを表示するアプリを作成する #6
kobayashi-shota/flutter_study pull request #20
Opened 2023-06-21 05:50 UTC by kobayashi-shota

# 概要
- #6

# 変更点
- NewsAPIのTopHeadlinesを取得
  - 取得したNewsのTile
    - タップするとWebView経由で閲覧
    - ロングプレスするとお気に入りに追加(jsonファイルで永続化)
  - お気に入りのNewsのTile
    - タップするとWebView経由で閲覧
    - 編集モードで削除

## 最新ニュース一覧
![Simulator Screen Recording - iPhone 14 Pro Max - 2023-06-21 at 14 39 32](https://github.com/kobayashi-shota/flutter_study/assets/82574685/3fb62e35-29ee-4b25-98fe-7f87b890dbe9)

## お気に入りの追加
![Simulator Screen Recording - iPhone 14 Pro Max - 2023-06-21 at 14 41 02](https://github.com/kobayashi-shota/flutter_study/assets/82574685/5b5a1f33-1810-4d15-aea5-3fe3691d42dd)

## お気に入りの削除
![Simulator Screen Recording - iPhone 14 Pro Max - 2023-06-21 at 14 41 18](https://github.com/kobayashi-shota/flutter_study/assets/82574685/bae4d02b-29ab-4a3f-8710-993be593164f)

## お気に入りの永続化確認
![Simulator Screen Recording - iPhone 14 Pro Max - 2023-06-21 at 14 45 32](https://github.com/kobayashi-shota/flutter_study/assets/82574685/b7259f33-a043-4647-b3a7-ca21298a01e4)

# 懸念点
- ちょっとFileChanged数が多くなりました
- api-keys.jsonは後ほど共有します

2023-06-21 15:12 UTC, MinatoIshiwata commented on lib/presentation/screen/news/news_favorites_screen.dart
> +          }
emptyの処理はListView入る前のほうが良いかもです🙋

2023-06-21 15:13 UTC, MinatoIshiwata commented on lib/presentation/screen/news/news_favorites_screen.dart
> +          );
favorites[index]は一度定数として宣言したほうが良いかと思います🙋

2023-06-21 15:18 UTC, MinatoIshiwata commented on lib/presentation/screen/news/news_headlines_screen.dart
> +    }
mapでまとめてから追加したら良さそうに思います🙋

2023-06-21 15:22 UTC, MinatoIshiwata commented on lib/presentation/screen/news/news_favorites_screen.dart
> +  List<Article> favorites = [];
final宣言しても利用できると思います🙋

2023-06-21 15:23 UTC, MinatoIshiwata requested changes
useCaseなど宣言していてとても良い設計になっているかと思います。
何点かコメントいたしました。
ご確認のほどよろしくお願いいたします。

2023-06-22 00:06 UTC, kobayashi-shota commented on lib/presentation/screen/news/news_favorites_screen.dart
> +          }
修正しました🙏🏻
[fix: favorites.isEmpty評価後にListView(or EmptyView)を生成する](https://github.com/kobayashi-shota/flutter_study/pull/20/commits/1a65dc122d1b751f3cd48953381aea27fad2a238)

2023-06-22 00:12 UTC, kobayashi-shota commented on lib/presentation/screen/news/news_favorites_screen.dart
> +          );
修正しました🙏🏻
[fix: favorites[index]は利用前にfinal宣言して定数化](https://github.com/kobayashi-shota/flutter_study/pull/20/commits/b082b5892d760eaf56a4f997346a98cf46ec02e8)

2023-06-22 02:51 UTC, kobayashi-shota commented on lib/presentation/screen/news/news_headlines_screen.dart
> +    }
修正しました🙏🏻
[fix: drawer初期化処理見直し＆別ファイル化](https://github.com/kobayashi-shota/flutter_study/pull/20/commits/c170ddc1d6766d3a25be70f9fb55654998ae4643)

2023-06-22 02:56 UTC, kobayashi-shota commented on lib/presentation/screen/news/news_favorites_screen.dart
> +  List<Article> favorites = [];
AnimationController使用してなかったので削除しました🙏🏻
[fix: 不要なcontrollerを削除](https://github.com/kobayashi-shota/flutter_study/pull/20/commits/1c05d86bcdbf46be13e19d11cc2e7bf3cf6ed967)

2023-06-22 05:42 UTC, MinatoIshiwata requested changes
@kobayashi-shota 
修正対応ありがとうございます。
2点確認があります。

▼1点目
同じアイテムをお気に入りに追加できる状態は想定どおりの実装でしょうか？
![Simulator Screen Shot - iPhone 14 Pro - 2023-06-22 at 14 37 01](https://github.com/kobayashi-shota/flutter_study/assets/44658075/a473cc54-4186-4cc7-a891-9678e8948957)

▼2点目
赤丸部分、nullと表示される部分は何が表示される予定でしょうか？
想定外の表示になりますでしょうか？
ご確認のほどよろしくお願いいたします。

![Simulator Screen Shot - iPhone 14 Pro - 2023-06-22 at 14 36 52](https://github.com/kobayashi-shota/flutter_study/assets/44658075/70f413de-22e5-4687-ad0f-76c37c642272)

2023-06-22 05:51 UTC, kobayashi-shota commented
@MinatoIshiwata 
ご指摘ありがとうございます、2点とも想定外の挙動のため修正します🙇🏻‍♂️

2023-06-22 08:44 UTC, kobayashi-shota commented
@MinatoIshiwata 
修正しました、再レビューお願いします🙏🏻
- [fix: 重複する記事はお気に入りに追加しない](https://github.com/kobayashi-shota/flutter_study/pull/20/commits/15993179e3e9cc97c54a8bacd09b87969f4fb4d3)
- [fix: String?のnull表示回避](https://github.com/kobayashi-shota/flutter_study/pull/20/commits/d5401eb6a5c653f40ece2d6d2a47ff8fcb6a6c44)

![Simulator Screen Recording - iPhone 14 Pro Max - 2023-06-22 at 17 42 08](https://github.com/kobayashi-shota/flutter_study/assets/82574685/f0c9cf56-2280-45bb-8960-dafc5c05d8df)

2023-06-23 04:35 UTC, closed without merging